# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
steer1:
  ID: 1
  Return_Delay_Time: 0
  Operating_Mode: 3
steer2:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 3
steer3:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 3
steer4:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 3
